### PR TITLE
fix spelling mistake in module config changed - fixes #997

### LINKED ISSUE #997: Spelling mistake in ProjectMessages/ProjectMessages.resx
**Describe the bug**
There is a spelling mistake in the message for Module Config Changed

**Steps To Reproduce**
1. Update a Module setting but then don't save/upload it

**Expected behavior**
Warning Message Dialog should read: `There are still changes not uploaded to your modules. You will lose these changes if you close the form. Do you really want to continue?` --- i.e. `lose` is the correct spelling

**Actual behavior**
Warning Message Dialog actually reads: `There are still changes not uploaded to your modules. You will loose these changes if you close the form. Do you really want to continue?`

**Details**
 - MobiFlight Version: 9.5.0
 - FlightSim: N/A
 - AddOn: N/A

### PR DESCRIPTION
**Pull request by thestonefox**
The sentence should read `lose` and not `loose`.

### CODE REVIEW

**Comment by neilenns** [comment]
@thestonefox Can you open a corresponding issue for this? Thanks!

**Comment by thestonefox** [comment]
> @thestonefox Can you open a corresponding issue for this? Thanks!

Sure no worries, I've done and linked the issue in the PR

**Comment by neilenns** [comment]
@thestonefox Great, thanks! Makes it easy for @DocMoebiuz when generating the release notes in the future :)

**Comment by neilenns** [comment]
Fixes #997

**Review by DocMoebiuz — APPROVED** [review]
Thanks!

**Pull request merged**
