### PR TITLE
Fix for issue #625: Adding devices under circumstances causes an exception

### PR DESCRIPTION
**Pull request by GioCC**
Pre-select a child item (at least one is always created) to prevent null reference

### CODE REVIEW

**Comment by MobiFlight-Admin** [comment]
Thanks for this pull request. Is there an issue for this and what does it fix it exactly?

**Review by DocMoebiuz — COMMENTED** [review]
Going over https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.select?view=windowsdesktop-6.0#System_Windows_Forms_Control_Select and reading what it does, I think it is a side-effect that we trigger the node to be selected.

In my opinion it would be even better to make sure we have a already one node selected when we expand the tree.

With the current proposed approach, if i have two modules, and 
* i first open the dialog
* Now the first node / module is preselected
* Now i expand the second module (node)
* Now I add a device

Expected result:
* New device is added under second module (node)

Actual result:
* New device is added under first selected module (node)

**Comment by DocMoebiuz** [comment]
In line 367 after we are doing 

```
cfgItem = null;
tempModule = getVirtualModuleFromTree();
```
we should definitely add a 

`if (tempModule == null) return;`

because the getVirtualModuleFromTree() will return "null" - so I should have checked in the first place.

**Comment by GioCC** [comment]
By "Module" you mean the parent node (i.e. the Arduino board)? In this case, first of all my wording is imprecise, because the issue does not arise when adding a module, but a... how is it called? Peripheral?
Anyway, I had not considered what happend with more that one board, I will look further into it. Thanks for pointing it out.

**Comment by GioCC** [comment]
I added the forced node selection when the user clicks (usually, left clicks) on a node and - probably redundant - when a node is expanded.
I also encountered a case of failed board programming, when the configuration could not be loaded causing a further exception upon trying to display it; i made a single change, a check against null, in `MobiFlight/MobiFlightModule.cs`.

**Review by DocMoebiuz — COMMENTED** [review]
I have to check on the Config == null check, because it doesn’t look right to me. The Config property is not implemented good, and when Config is null it should fetch it from the Audi o board on the fly again.

the other changes are all OK.

**Comment by GioCC** [comment]
[THIS](https://github.com/MobiFlight/MobiFlight-Connector/commit/76b0509e9ecac649694fc4bf2f653cd3e26f1692) commit has wrecked the PR (and then some). I will probably have to do everything from scratch otherwise there's risk of leaving bugs around. Not very eager about that.

**Comment by GioCC** [comment]
So what you suggest to do about the Config == null check? It probably made its way in during testing, but it's not strictly part of this PR... I could remove it from here and see to opening a new issue about it.

**Comment by moebigit** [comment]
if it was by accident then i would remove it.

**Comment by GioCC** [comment]
Done!

**Comment by GioCC** [comment]
I lost sight of this for a little, is there anything else to fix? To me it should be OK.

**Review by DocMoebiuz — APPROVED** [review]
Thanks!

**Comment by DocMoebiuz** [comment]
Fixed #625

**Comment by GioCC** [comment]
Unfortunately I discovered that this fix introduces a further bug - will post issue and fix shortly.

**Pull request merged**
