### PR TITLE
Added & fixed PMDG DC-6 Lvars

### PR DESCRIPTION
**Pull request by flightdeck-to**
Added PMDG DC-6 Lvars for:

- Gyropilot
- Superchargers
- Fuel boost
- Anti-ice
- Tablet AFE controls
- Cowl flaps

Fixed PMDG-DC-6 Lvars for:
- Gyropilot ALT HOLD
- Gyropilot AP toggle

Fixed naming:
-  AP toggle
-  AP Lever toggle

All LVars have been tested with the latest version (2.0.36)

### CODE REVIEW

**Comment by Mobiflight** [comment]
@rofl-er  can you please review this

**Comment by rofl-er** [comment]
@flightdeck-to Thank you for your contribution! Since some weeks now, have implemented a dedicated system to contribute your findings to the MobiFlight community called HubHop which you can find here: https://hubhop.mobiflight.com/#/ . This system is also our database for all events/variables which you can find inside MobiFlight.

Updating the events.txt file directly will brake our "routine" of exporting the current Dataset from HubHop and importing it into the MF connector.

If you agree, I would suggest that you update the events directly on HubHop and I will export the latest presets. Let me know what you think.

**Comment by flightdeck-to** [comment]
I'll add them to hubhop, thanks!

**Comment by MobiFlight-Admin** [comment]
Awesome!

**Pull request closed without merging**
