### PR TITLE
854 fw debug prints

### LINKED ISSUE #854: Add firmware debug printouts to log
**Is your feature request related to a problem? Please describe.**
Debug printouts from the firmware should show up in the log.

**Describe the solution you'd like**
Until now debug printouts are marked as `kStatus`. These printout should get an own identifier and when reieved added to the log in case of debug loglevel is activated

**Describe alternatives you've considered**
none

**Additional context**
The firmware must be cahnged accordingly. A separate issue will be opened in the firmware repo, see issue 188

### PR DESCRIPTION
**Pull request by elral**
Firmware debug infos will be printed to the console if log level is debug.

Fixes #854

### CODE REVIEW

**Review by DocMoebiuz — COMMENTED** [review]
Hi Ralf, sorry - I was not able to review earlier..

Let's add the module name to the debug message:

$"{this.Name}.{debug}: {value1} {value2} {value3}"

**Comment by elral** [comment]
Hi Sebastian,
sorry, I tried to change it but it fails.
image
I have no idea how to change it :(
Also how to add that it is coming from the firmware.
Regards
Ralf

**Comment by DocMoebiuz** [comment]
> Hi Sebastian,
> sorry, I tried to change it but it fails.
> image
> I have no idea how to change it :(
> Also how to add that it is coming from the firmware.
> Regards
> Ralf

debug is no variable and can't be substituted. Remove the curly braces from {debug}.

**Review by DocMoebiuz — APPROVED** [review]
Thanks! And sorry for the long delay in approving.

**Pull request merged**
