### PR TITLE
Use TryParse() instead of Parse()

### LINKED ISSUE #1105: Crash when initializing a multiplexer
**Describe the bug**
User in Discord reported a crash when attempting to use a multiplexer in version 9.6.0.

```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at MobiFlight.Config.MultiplexerDriver.Initialize(String[] pinNos)
   at MobiFlight.Config.MultiplexerDriver.FromInternal(String value)
```

image

The offending line of code is here:

https://github.dev/MobiFlight/MobiFlight-Connector/blob/b4cf773cef7f5c48de6fb215470f1b299ae3bc44/MobiFlight/Config/MultiplexerDriver.cs#L56-L57

Still not sure *why* this is happening but the code can definitely be tweaked to not crash.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #1105

No idea what the root cause of this is but at least it won't crash anymore.

### CODE REVIEW

**Review by GioCC — APPROVED** [review]

**Comment by GioCC** [comment]
Parse() is one of the things that always bugged me in C#... I mean, I understand that raising exceptions should be the ortodox way to go, but I always felt more natural to use TryParse() in the first place (and somehow the way I'd expect Parse() to work).

**Comment by neilenns** [comment]
Yeah I don't even like tryparse. Out parameters just seem wrong. But that's what happens when APIs predate nullable types by like... A decade? 15 years?

**Comment by DocMoebiuz** [comment]
What bugs me: why are we getting these types of errors recently? the fix addressing only the symptom, not the cause (you said it already too)...

**Review by DocMoebiuz — COMMENTED** [review]
I can see this in line#68 - cant link to it from the comments here because there was no change

Ah hold on, after a reset I see this: 
image

**Comment by neilenns** [comment]
I'm hoping the user tries the build I gave them and pastes the log in so I can see what the value is and chase down why it is wrong.

The other cases had a known cause: external interference causing corrupted serial transmission. I doubt that is the case here though...


________________________________

**Comment by DocMoebiuz** [comment]
> I'm hoping the user tries the build I gave them and pastes the log in so I can see what the value is and chase down why it is wrong. The other cases had a known cause: external interference causing corrupted serial transmission. I doubt that is the case here though...
> […](#)
> ________________________________ From: Sebastian M ***@***.***> Sent: Monday, January 30, 2023 3:25:54 PM To: MobiFlight/MobiFlight-Connector ***@***.***> Cc: Neil Enns ***@***.***>; Author ***@***.***> Subject: Re: [MobiFlight/MobiFlight-Connector] Use TryParse() instead of Parse() (PR #1106) @DocMoebiuz commented on this pull request. I can see this in line#68 - cant link to it from the comments here because there was no change Ah hold on, after a reset I see this: [image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F86157512%2F215619567-5f122bfd-a99e-4a28-a0ed-564894082e9c.png&data=05%7C01%7C%7C80a896c3dd714531e9cf08db03195618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107179572311975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2Z73gX08%2B1c0q0uBR0xIfPJYM9RyobPhahHAgvujUXQ%3D&reserved=0> — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMobiFlight%2FMobiFlight-Connector%2Fpull%2F1106%23pullrequestreview-1276182402&data=05%7C01%7C%7C80a896c3dd714531e9cf08db03195618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107179572311975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2XFeTcIEKjkzEP7OwCwmnk%2Ffim%2FloifkoTlZRt37Oi0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACIVHFVIFHVIYRV77F5BN4LWVBEYFANCNFSM6AAAAAAULOIOEI&data=05%7C01%7C%7C80a896c3dd714531e9cf08db03195618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638107179572311975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z0h3I4j%2F1M3NyEg7vuc9C%2FjvMCPhMYM4aDswbw6e3R0%3D&reserved=0>. You are receiving this because you authored the thread.Message ID: ***@***.***>

Please check in which circumstances Reset() is called and then Initialize() - i mean there we have a state where the pins are less than 0

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
Let's figure out why the pins are still in their init state.

**Comment by neilenns** [comment]
@GioCC Can you look into that? I'm not familiar with this code at all, this was just a quick fix to not crash.

**Comment by GioCC** [comment]
Of course, I'll have a look ASAP.

**Comment by GioCC** [comment]
> why are we getting these types of errors recently?
Can you maybe remember any related incident? I could use additional clues.

**Comment by MobiFlight-Admin** [comment]
> > why are we getting these types of errors recently?
> 
> Can you maybe remember any related incident? I could use additional clues.

the reported issues were of a different nature, they had to do with faulty values on serial line. it think this part of the code is different

**Comment by DocMoebiuz** [comment]
oh no, I had written a long feedback and now it is gone.. .closed the tab by accident :(

**Review by DocMoebiuz — APPROVED** [review]

**Comment by DocMoebiuz** [comment]
Follow up is #1110

**Pull request merged**
