### PR TITLE
Add setting to control minimize on autorun

### LINKED ISSUE #1317: Add a setting to disable auto-minimize on auto-run
**Is your feature request related to a problem? Please describe.**
Right now if auto-run is enabled MobiFlight will always minimize to the system tray when it starts running. This is really annoying when you have MobiFlight open in another window because you want to see the logs, or are working to edit configurations.

**Describe the solution you'd like**
A setting that disables the minimizing behaviour on auto-run.

**Describe alternatives you've considered**
Turning off auto-run, but then I lose the benefit of auto-run.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #1317 

* Rename an existing section of the general settings dialog to "Run options" so I don't have to add another section with a single setting in it
* Add a general setting "Minimize to system tray on AutoRun", which defaults to true to maintain existing behaviour by default
* Check that setting before attempting to minimize the app

image

@DocMoebiuz If you give me the German translation for that string I can add it to the string resources for the dialog

### CODE REVIEW

**Comment by neilenns** [comment]
Just pushed a change to fix the tab order in the general settings as well.

**Comment by DocMoebiuz** [comment]
> Fixes #1317
> 
> * Rename an existing section of the general settings dialog to "Run options" so I don't have to add another section with a single setting in it
> * Add a general setting "Minimize to system tray on AutoRun", which defaults to true to maintain existing behaviour by default
> * Check that setting before attempting to minimize the app
> 
> image
> @DocMoebiuz If you give me the German translation for that string I can add it to the string resources for the dialog

German translation: "Bei AutoRun in Task Leiste minimieren"

**Comment by neilenns** [comment]
@DocMoebiuz Can I also get for "Run options"?

**Comment by DocMoebiuz** [comment]
> @DocMoebiuz Can I also get for "Run options"?

"Run" Optionen

**Pull request merged**
