### PR TITLE
Auto width for Module, Input, Output and Type

### LINKED ISSUE #1533: Remember grid view column widths across app launches
**Is your feature request related to a problem? Please describe.**
It's possible to resize the column widths on the Outputs and Inputs tab, but those widths aren't persisted across app launch. When you get them sized the way you like you'll lose it when you quit Mobiflight then re-launch.

**Describe the solution you'd like**
Remember the column widths across app launch.

**Additional context**
[Requested by Glenn in Discord](https://discord.com/channels/608690978081210392/745361245808492584/1189360726964437062)

I asked ChatGPT and this is totally possible to do without too much effort.

### PR DESCRIPTION
**Pull request by Koseng**
Fixes #1533. Or better, fixes the root cause for the wish of #1533.

I'm also annoyed by the truncated or wrapped texts and all the time need to adjust the columns, so everything is visible.

I propose to just auto size Module, Input, Output and Type based on the content. Why not? Try it.

Opinions @neilenns , @DocMoebiuz ?

### CODE REVIEW

**Comment by neilenns** [comment]
Ooooh. I'll give this a try later today, could be a lot easier than what I was looking at doing (storing the manually set widths in the config files).

**Comment by DocMoebiuz** [comment]
I tried with a bigger config and the resource consumption goes up a lot. UI is not responsive and takes several seconds until the config is loaded. Maybe first load the config, and then set the columns to auto-width. It might re-calcualte it otherwise multiple times while loading the data.

**Comment by DocMoebiuz** [comment]
[aero2023-combined-display.mcc.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/13798207/aero2023-combined-display.mcc.txt)

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
see my attached config and the comment about performance on opening the file.

**Comment by Koseng** [comment]
Good catch, now performance fix included.

**Comment by DocMoebiuz** [comment]
> Good catch, now performance fix included. Does that fix it for you?

yes. it opens the file like before.

**Review by DocMoebiuz — APPROVED** [review]

**Pull request merged**
