### PR TITLE
Catch exceptions when converting input values to integers

### LINKED ISSUE #1051: MobiFlight crashes when analog input value can't be converted to a number
**Describe the bug**
MobiFlight crashes when analog input value can't be converted to a number. Reported by Jaime in Discord.

```
Application: MFConnector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at MobiFlight.MobiFlightModule.OnAnalogChange(CommandMessenger.ReceivedCommand)
   at CommandMessenger.CmdMessenger.InvokeCallBack(MessengerCallbackFunction, CommandMessenger.ReceivedCommand)
   at CommandMessenger.CmdMessenger.HandleMessage(CommandMessenger.ReceivedCommand)
   at CommandMessenger.Queue.ReceiveCommandQueue.ProcessQueue()
   at CommandMessenger.AsyncWorker.<Start>b__20_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #1051 

Jaime wasn't able to reproduce the problem with a private build containing this fix. Even so, it's clear it *could* happen in code.

* Add a try/catch around the value parsing
* Tidy up the code for calling the event handler since VS suggested a simpler way to do it while I was editing the method

### CODE REVIEW

**Comment by neilenns** [comment]
Jaime hit the same issue with buttons so I added the same changes to the button code as well.

**Comment by DocMoebiuz** [comment]
the firmware should not be able to produce non integer numbers. In which circumstances would the number not be an int?

**Comment by neilenns** [comment]
Noise on the line causing issues with the serial communication.

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
Please take a look at https://github.com/neilenns/MobiFlight-Connector/blame/9c78c849c24a88800d2316ebf0ace3e93202eee4/MobiFlight/MobiFlightModule.cs#L505

for some reason the Encoder was already having a similar check, which in my opinion is easier to read. 

In any case we would like to harmonize the approaches and make it the same for all three cases. My preference is the short way (encoder) but it lacks the log statement.

**Comment by neilenns** [comment]
Updated to use `TryParse()` instead and made sure all inputs use the same pattern (input shifter and multiplexers also needed this code).

**Review by DocMoebiuz — APPROVED** [review]
Thank You!

**Pull request merged**
