### PR TITLE
Add try/catch for invalid PMDG input event values

### LINKED ISSUE #1006: Crash at PmdgEventIdInputAction.execute when converting value to UInt32
**Describe the bug**
Reported by hrings in Discord. MobiFlight crashes and reports this in the event log:

```
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseUInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at MobiFlight.InputConfig.PmdgEventIdInputAction.execute(MobiFlight.InputConfig.CacheCollection, MobiFlight.InputEventArgs, System.Collections.Generic.List1<MobiFlight.ConfigRefValue>)
   at MobiFlight.InputConfigItem.execute(MobiFlight.InputConfig.CacheCollection, MobiFlight.InputEventArgs, System.Collections.Generic.List1<MobiFlight.ConfigRefValue>)
   at MobiFlight.ExecutionManager.mobiFlightCache_OnButtonPressed(System.Object, MobiFlight.InputEventArgs)
   at MobiFlight.MobiFlightCache.module_OnButtonPressed(System.Object, MobiFlight.InputEventArgs)
   at MobiFlight.MobiFlightModule.OnAnalogChange(CommandMessenger.ReceivedCommand)
```

Offending line is:

https://github.dev/MobiFlight/MobiFlight-Connector/blob/5e62a246756c16203d9a3c171f2cdab307afafd7/MobiFlight/InputConfig/PmdgEventIdInputAction.cs#L75-L76

There should probably be a try/catch around this at a minimum to guard against the crash.

Config file: [config.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/10003829/config.zip)

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #1006 

I did look at other places higher up to add a try/catch and didn't see anywhere obvious to cleanly add one.

### CODE REVIEW

**Comment by DocMoebiuz** [comment]
i was thinking about a line like this: https://github.com/neilenns/MobiFlight-Connector/blob/c9d875dff1ff36e8408e261cafad34c783aaf676/MobiFlight/ExecutionManager.cs#L1440 where the input actions are executed

**Comment by neilenns** [comment]
Thanks, will add something there.

**Comment by neilenns** [comment]
@DocMoebiuz Added the extra try/catch

**Review by DocMoebiuz — APPROVED** [review]
Thank you!

**Pull request merged**
