### PR TITLE
Make the analog pin dropdown wider

### LINKED ISSUE #801: Pin selection dropdown is too narrow for analog inputs
Reported by Mickey's Flightdeck in Discord.

**Describe the bug**

The dropdown is too narrow and you can't tell that this is pin A10 instead of A1

https://media.discordapp.net/attachments/745361245808492584/973310538270539786/unknown.png

**Steps To Reproduce**
1. Add a new analog input device to a connected board
2. Change the pin to a two digit pin (e.g. A10)

**Expected behavior**
See A10 in the dropdown

**Actual behavior**
See A1 in the dropdown

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #801 

Make the dropdown wider and move the pin label over a bit to make room for the wider dropdown.

image

### CODE REVIEW

**Comment by neilenns** [comment]
Apparently some of the other device types have this issue as well, I'll update the pr with those later today

**Comment by neilenns** [comment]
**LED Output**

image

**Servo**

image

**Stepper**

image

**Encoder**

image

**Button**

image

**Multiplexers**

image

**Comment by neilenns** [comment]
Still need to fix the input shifter, output shifter, and 7-segment LED panels. They're more of a pain since they have a lot of dropdowns in a single line.

**Comment by DocMoebiuz** [comment]
@neilenns Thanks!!! did you check the German UI version for label position? It might just be OK!

**Comment by neilenns** [comment]
@DocMoebiuz I did not. Who uses German anyway!????!!!??? 😂

I'll try fixing the other ones later today and will confirm German works.

**Comment by DocMoebiuz** [comment]
@neilenns what happened to this? can you finish it so that i can merge it?

**Comment by neilenns** [comment]
Two trips back to back to visit family happened 😭 won't be able to finish until next week.

**Review by DocMoebiuz — APPROVED** [review]
Thanks

**Pull request merged**
