### PR TITLE
Increase the number of supported multiplexer devices

### LINKED ISSUE #950: Increase the supported Mux for Mega to 3 devices
Connector side for https://github.com/MobiFlight/MobiFlight-FirmwareSource/issues/194

Need to update the values in the board.json files for each board.

### PR DESCRIPTION
**Pull request by GioCC**
Fixes #950

Related to FW: 
issue [#194](https://github.com/MobiFlight/MobiFlight-FirmwareSource/issues/194)
PR [#209](https://github.com/MobiFlight/MobiFlight-FirmwareSource/pull/209)

Number of multiplexer devices increased from 2-1-2 (Mega/ProMicro/Uno) to 4-3-3.

### CODE REVIEW

**Review by DocMoebiuz — APPROVED** [review]
Thanks.

**Comment by RamsesTwo** [comment]
Hello Guys, 
I love the use of the Multiplexer, 
The increse to 4 DataPin for the Mega was nice... in this Version 
My current project is all done for a MCDU A320 PCBoard etc.. Using only one Mega + one Mux

Except for the fact that I depend on 11 DataPin in link with the Multiplexer
Now Mobiflight deal with only 4 for the Mega ...
It would be so easy for you guys to increase that limit to 11 or more ... I so mutch depend on it ... please .....
What would it take in Donation to have you increase that limit of 4 to 11 (my need) or more ???
Hope to ear from you Guys soon ....
MCDU Airbus Matrix

**Comment by GioCC** [comment]
> Except for the fact that I depend on 11 DataPin in link with the Multiplexer Now Mobiflight deal with only 4 for the Mega ... 
Hi RamsesTwo, would you please join us on the MobiFlight Discord channel? It's a more appropriate place for these discussions. 
That is indeed feasible, I can give you some pointers.If you want to contact me there by PM, I go by the same nickname.

**Comment by RamsesTwo** [comment]
Hello GioCC cant find the way to contact you in a PM message in this Github site ?
And not sure where that MobiFlight Discord channel ? is
Cant wait to exchange on the subject with you...
I take a chance me e mail is:   Pierreboudr@hotmail.com
Thanks for your replie

**Comment by DocMoebiuz** [comment]
To me it looks like that you are looking for a matrix support - like a keyboard matrix rather then multiplexer

**Comment by RamsesTwo** [comment]
Hello Doc you are wright in a sence... It is quite similar to a keyboard matrix configuration...
But with ( n ) Multiplexer combine with ( n ) DataPin I can get exactly their and keep the design to it simple configuration
I am right now able to have the design working for the 4th down row Data 09 to 12 and Good it work like a Charm.. All I need is to have 11 Data instead of 4  :-)  I hope GioCC will help me... Have a Good Day Doc ;-)

**Comment by DocMoebiuz** [comment]
As i understand you are asking to up the limit from 4 Multiplexers to 11 so that you get 176 additional pins.

You can do that for testing purpose on your own by editing and building a custom firmware.

At the moment it's rather unlikely that we up the limit to 11 for the official build.

On the other hand I know that we have actual matrix support in the makes. that would support a 6x6 matrix.

**Pull request merged**
