### PR TITLE
Fix analog pin assignments for output shift registers

### LINKED ISSUE #470: Analog pins don't work correctly with shift registers
**Describe the bug**

The UI for setting clock/data/latch for output shift registers doesn't work correctly with analog pins.

**Steps To Reproduce**
1. Add a new output shift register to the MobiFlight modules
2. Set any of the clock/data/latch dropdowns to an analog pin (e.g. A0)
3. Upload the config to the Arduino
4. Close the modules dialog
5. Open the modules dialog again and try to edit the output shift register

**Expected behavior**
Output shift register settings display and can be edited

**Actual behavior**
An empty page

The issue is in two places:

* https://github.dev/MobiFlight/MobiFlight-Connector/blob/df2513e81c2719d6c3cbe70e5a30e43d9fb39a5a/UI/Panels/Device/MFShiftRegisterPanel.cs
* https://github.dev/MobiFlight/MobiFlight-Connector/blob/df2513e81c2719d6c3cbe70e5a30e43d9fb39a5a/UI/Panels/Device/MFShiftRegisterPanel.cs

### PR DESCRIPTION
**Pull request by danecreekphotography**
Fixes #470 

Change how the shift register selected pins are initialized when the panel is created, and how they are saved when the dialog is changed.

While this resolves the error with the dialog I have not been able to confirm whether the analog pins actually work.

### CODE REVIEW

**Comment by danecreekphotography** [comment]
There's still something not working here, will re-open in a bit.

**Comment by danecreekphotography** [comment]
Never mind. This is fine, I was just on the wrong branch locally. Sigh.

**Comment by MobiFlight-Admin** [comment]
I don'tget pull; request notifications from github
that is kind of weird

**Comment by danecreekphotography** [comment]
Hmm, interesting. There's probably a project setting to turn it on so admins get notified. I would have tagged you as a reviewer regardless but I'm not a contributor on the repo so I can't add reviewers.

**Comment by MobiFlight-Admin** [comment]
i have checked already. i am getting notifications for comments, i will double check if i get it for PRs

**Pull request merged**
