### PR TITLE
Make SimConnect the default for new output configs

### LINKED ISSUE #562: Make SimConnect (MSFS2020) the default output variable type
The vast majority of people are flying MSFS2020 now, but when they try and make an output it defaults to FSUIPC Offset which shouldn't be used with FS2020.

Make the default MSFS2020.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #562

### CODE REVIEW

**Comment by MobiFlight-Admin** [comment]
Hi Neil - thanks and yeah, that's an easy fix :D Let us also change the order in the Config Wizard. So that the FSUIPC Offset goes last.

Additional info: When I implemented the support for the MSFS SimVars, I refactored a lot of code and when I had to decide whether FSUIPC should be default or MSFS2020 could be default, I was not 100% if I had used the type consistently in (very) old configs.

I have checked now again in the git history and I believe it should definitely be a backward compatible change.

**Comment by neilenns** [comment]
@MobiFlight-Admin Updated the position of the radio buttons. WPF changes cause a lot of churn, good grief.

image

**Comment by MobiFlight-Admin** [comment]
@neilenns - thanks mate! Sorry to be annoying... let's move FSUIPC all the way over when we are at it :)

**Comment by MobiFlight-Admin** [comment]
I am thinking of really disabling the FSUIPC support as a global flag (someone has brought it up, i think it was Jaime). It would make the interface then specific to MSFS2020 and would not show FSUIPC at all. But that would be beyond this task for sure.

For now, let's move FSUIPC to the right.

**Comment by neilenns** [comment]
@MobiFlight-Admin Done!

image

**Comment by MobiFlight-Admin** [comment]
Woohoo!

**Pull request merged**
